###############################################################################
# Version: v2.1.0
# Author:  xflm
# Date:    Fri Feb 26 17:03:14 CST 2021
###############################################################################

# Define toolchain path
TOOLCHAIN = 

# Define template path
TEMPLATE = .

# Define target name
TARGET = hello

# Define board name: 
BOARD = 

# Define target type: exe lib
TARGET_TYPE = exe
#TARGET_TYPE = lib

# Define build type: (null) debug profile release
#BUILD_TYPE =
#BUILD_TYPE = debug
BUILD_TYPE = profile
#BUILD_TYPE = release

# Append global macro
USERDEFINES = 

# Append standard library
USERSTDLIB = 

# Append GCC flags
USERCFLAGS = 

# Append LD flags
USERLDFLAGS = 

# Use vpath mode, y is enable, default is disable
VPATH_MODE = 

# Use garbage collection mode, y is enable, default is disable
GARBAGE_COLLECTION = y

# Create files, y is create, default is not create
CREATE_DIS = 
CREATE_ASM = 
CREATE_BIN = 
CREATE_HEX = 
CREATE_MAP = 
CREATE_GC  = 

# Define shell cmd, run before and after compile
# like: CMD_BEFORE = echo -n ===; echo ===
CMD_BEFORE = 
CMD_AFTER = 

include $(TEMPLATE)/tools/make/make.mk
